package com.kland.wd.dto;

import lombok.Data;

import java.util.Date;

/**
 * mysql库实体类
 */
@Data
public class AccMsgDto {

    private int id;   //int NOT NULL AUTO_INCREMENT,
    private String control_type;   //(255) DEFAULT NULL COMMENT '管控类型',
    private String attachment;   //(255) DEFAULT NULL COMMENT '附件',
    private String nick_name;   //(255) NOT NULL COMMENT '昵称',
    private String site_name;   //(255) NOT NULL COMMENT '网站',
    private String group_id;   //(255) DEFAULT NULL COMMENT '群ID',
    private String public_id;   //(255) DEFAULT NULL COMMENT '公众号',
    private Date create_time; // datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    private Date dispose_time; // datetime DEFAULT NULL COMMENT '处置时间',
    private int upload_task_id; // bigint DEFAULT NULL,
    private String msg_id;   //(255) DEFAULT NULL COMMENT '消息ID',
    private String publish_time_str;   //(255) DEFAULT NULL COMMENT '发布时间',
    private String dispose_user;   //(255) DEFAULT NULL COMMENT '岗位值班员',
    private String orgin_id;   //(255) DEFAULT NULL COMMENT '原发ID',
    private String page_no;   //(255) DEFAULT NULL,
    private int update_user_id;// bigint DEFAULT NULL,
    private Date update_time;// timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    private Date publish_time;// datetime DEFAULT NULL COMMENT '发布时间',
    private String user_id;   //(255) DEFAULT NULL COMMENT '用户ID',
    private String local;   //(255) DEFAULT NULL COMMENT '地域',
    private int fans_num;   //int DEFAULT NULL COMMENT '粉丝数',
    private String index_msg;   //(255) DEFAULT NULL COMMENT '查询索引用',
    private String dispose_time_str;   //(255) DEFAULT NULL COMMENT '处置时间字符串',
    private String image;   //(255) DEFAULT NULL COMMENT '图片',
    private String url;   //(255) DEFAULT NULL COMMENT '消息URL',
    private String msg_type;   //(255) DEFAULT NULL COMMENT '消息类型',
    private String type;   //(255) DEFAULT NULL,
    private String dispose;   //(255) DEFAULT NULL COMMENT '处置措施',
    private String remark;   //(255) DEFAULT NULL COMMENT '备注',
    private String site_channel;   //(255) DEFAULT NULL COMMENT '平台',
    private String basic_desc;// text COMMENT '账号基本描述',
    private String illegal_reason;// text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '违规原因分析',
    private String illegal_records;   //(255) DEFAULT NULL COMMENT '违规记录',
    private String recommend_account;   //(255) DEFAULT NULL COMMENT '推荐账号',
    private String txpass;   //(255) DEFAULT NULL COMMENT '通行证',
    private String registerIp;   //(255) DEFAULT NULL COMMENT '用户注册IP',
    private String bindphone;   //(255) DEFAULT NULL COMMENT '用户绑定手机',
    private Date registerTime;// datetime DEFAULT NULL COMMENT '注册时间',
    private String isban;   //(255) DEFAULT NULL COMMENT '是否被封号',
    private String baseInfo;// text COMMENT '基本信息',
    private String content;   //(255) DEFAULT NULL COMMENT '发布内容、消息内容，内容',
    //    private String grealName;   //(25) DEFAULT NULL COMMENT '个人真实姓名',
//            `gSex;   //(15) DEFAULT NULL COMMENT '个人性别',
//            `gbirthDate` date DEFAULT NULL COMMENT '个人出生日期',
//            `geducBackGround;   //(25) DEFAULT NULL COMMENT '个人教育背景',
//            `gPhoneNumber;   //(35) DEFAULT NULL COMMENT '个人手机号',
//            `gMailbox;   //(55) DEFAULT NULL COMMENT '邮箱',
//            `gIDType;   //(25) DEFAULT NULL COMMENT '证件类型',
//            `gIDNumb;   //(65) DEFAULT NULL COMMENT '证件号',
//            `gProvince;   //(35) DEFAULT NULL COMMENT '省',
//            `gCity;   //(35) DEFAULT NULL COMMENT '市',
//            `gAddress;   //(65) DEFAULT NULL COMMENT '所在地址',
//            `gCompany;   //(65) DEFAULT NULL COMMENT '所在公司',
//            `gDescribe;   //(85) DEFAULT NULL COMMENT '个人描述',
//            `fromDepart;   //(55) DEFAULT NULL COMMENT '所属单位，账号数据来自哪个局',
    private String createUserId;   //(55) DEFAULT NULL COMMENT '录入人userId',
    private String createUserName;   //(55) DEFAULT NULL COMMENT '录入人用户名',
    private String createUserdept;   //(55) DEFAULT NULL COMMENT '录入人部门',
    private String authInfo;   //(155) DEFAULT NULL COMMENT '认证信息',
    private int attentionNum;   //int DEFAULT NULL COMMENT '关注数',
    private int postNum;   //int DEFAULT NULL COMMENT '发帖数',
    private String zsRecomRes;   //(255) DEFAULT NULL COMMENT '转世推荐原因',
    private int relaParentId;   //int DEFAULT NULL,
    private int zsParentId;   //int DEFAULT NULL,
    private int isRecommend;   //int unsigned DEFAULT '0',
    private int isMasterAccount;   //int DEFAULT '0' COMMENT '是否主账号，1是，2否',
    private int zsaccountnum;   //int DEFAULT '0' COMMENT '转世账号条数',
    private int states;   //int DEFAULT '0' COMMENT '是否启用,0否，1是',
    private int recaccountnum;   //int DEFAULT '0' COMMENT '引擎推荐账号数',
    private String thirdauthaccount;   //(45) DEFAULT NULL COMMENT '第三方认证类型及编号',
    private String sourcesinform;   //(45) DEFAULT NULL COMMENT '来源信息',
    private int logid;   //int DEFAULT NULL,
    private String iconpath;   //(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_icelandic_ci DEFAULT NULL,
    private int accountUserId;   //int DEFAULT NULL,
    private String zhztlb;   //(45) DEFAULT NULL COMMENT '账号主体类别',
    private String zhyynrlb;   //(45) DEFAULT NULL COMMENT '账号运营内容类别',
    private String zhfj;   //(45) DEFAULT NULL COMMENT '账号分级',
    private String czbq;   //(45) DEFAULT NULL COMMENT '处置标签',
    private String sfhmd;   //(45) DEFAULT NULL COMMENT '是否为企业标注黑名单',
    private Date markTime;// timestamp(6) NULL DEFAULT NULL COMMENT '研判时间',
    private int recStates;   //int DEFAULT '0',
    private String gasp;   //(45) DEFAULT NULL COMMENT '渠道平台，同步mpp库和神通库字段',
    private Date recTime;// timestamp(6) NULL DEFAULT NULL COMMENT '账号引擎分析时间',
    private Date u_snapshot_time;// datetime DEFAULT NULL,
    private Date u_gather_time;// datetime DEFAULT NULL,
    private int uo_status;   //int DEFAULT NULL,
    private int site_acc_from;   //int DEFAULT '-1',}

}
